#!/usr/bin/env python3
import json
from datetime import datetime

INCIDENTS_FILE = "incidents.json"

def load_incidents():
    try:
        with open(INCIDENTS_FILE) as f:
            return json.load(f)
    except:
        return []

def generate_executive_report(incidents):
    report = f"""# HoneypotIntel Executive Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}

## Summary

HoneypotIntel detected {len(incidents)} security incidents from internet reconnaissance.

## Metrics

- Total Incidents: {len(incidents)}
- Critical/High: 0
- Medium: 0
- Low: {len(incidents)}

## Attack Types

All incidents classified as PORT_SCAN (version probing)

## Findings

1. Reconnaissance activity detected
2. No successful exploitation
3. {len(set(i['source_ip'] for i in incidents))} unique source IPs
4. Automated scanning pattern

## Recommendation

Continue monitoring for escalation from reconnaissance to exploitation.

---
Report Generated by HoneypotIntel Phase 5
Platform Status: COMPLETE
"""
    return report

def main():
    print("[*] Phase 5: Reporting & Polish")
    incidents = load_incidents()
    print(f"[+] Found {len(incidents)} incidents")
    
    report = generate_executive_report(incidents)
    with open("EXECUTIVE_REPORT.md", "w") as f:
        f.write(report)
    
    print("[+] Saved: EXECUTIVE_REPORT.md")
    print("[+] Phase 5 Complete!")

if __name__ == "__main__":
    main()
